/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:573225:
  appc.background(230);
} //_CODE_:window1:573225:

public void CarName(GTextField source, GEvent event) { //_CODE_:Carname:612597:
  carname = Carname.getText();
} //_CODE_:Carname:612597:

public void Horsepower(GCustomSlider source, GEvent event) { //_CODE_:HP:609414:
  hpInput = HP.getValueF();
} //_CODE_:HP:609414:

public void Torque(GCustomSlider source, GEvent event) { //_CODE_:TQ:343920:
  tqInput = TQ.getValueF();
} //_CODE_:TQ:343920:

public void RPMlim(GCustomSlider source, GEvent event) { //_CODE_:RPM:797981:
  rpmInput = RPM.getValueF();
} //_CODE_:RPM:797981:

// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 300, 200, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(window1, 69, 23, 162, 19);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Car Performance Analyzer");
  label1.setOpaque(false);
  label2 = new GLabel(window1, 53, 58, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Car Name:");
  label2.setOpaque(false);
  label3 = new GLabel(window1, 53, 90, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Horsepower");
  label3.setOpaque(false);
  label5 = new GLabel(window1, 52, 156, 80, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("RPM Limit");
  label5.setOpaque(false);
  label4 = new GLabel(window1, 53, 123, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Torque");
  label4.setOpaque(false);
  Carname = new GTextField(window1, 140, 59, 120, 20, G4P.SCROLLBARS_NONE);
  Carname.setText("Car Name");
  Carname.setOpaque(true);
  Carname.addEventHandler(this, "CarName");
  HP = new GCustomSlider(window1, 141, 80, 100, 40, "grey_blue");
  HP.setLimits(100.0, 100.0, 1200.0);
  HP.setNumberFormat(G4P.DECIMAL, 2);
  HP.setOpaque(false);
  HP.addEventHandler(this, "Horsepower");
  TQ = new GCustomSlider(window1, 141, 115, 100, 40, "grey_blue");
  TQ.setTextOrientation(G4P.DECIMAL);
  TQ.setLimits(100.0, 100.0, 1200.0);
  TQ.setNumberFormat(G4P.DECIMAL, 2);
  TQ.setOpaque(false);
  TQ.addEventHandler(this, "Torque");
  RPM = new GCustomSlider(window1, 141, 146, 100, 40, "grey_blue");
  RPM.setLimits(1200.0, 1200.0, 10000.0);
  RPM.setNumberFormat(G4P.DECIMAL, 2);
  RPM.setOpaque(false);
  RPM.addEventHandler(this, "RPMlim");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GLabel label1; 
GLabel label2; 
GLabel label3; 
GLabel label5; 
GLabel label4; 
GTextField Carname; 
GCustomSlider HP; 
GCustomSlider TQ; 
GCustomSlider RPM; 
